### ISSUE TITLE
Only display the name of the conda-enviroment

### ISSUE THREAD

**Issue by matchai** [matchai/spacefish#139]
Please take a look at the associated PR: https://github.com/denysdovhan/spaceship-prompt/pull/597

## 

> [🐟](https://github.com/matchai/spacefish-bot) **spacefish-bot** — Issue copied from: https://github.com/denysdovhan/spaceship-prompt/issues/589.

I often use (due to company-policy where to place things) conda-enviroments, which are not in the default conda-envs folder. Spaceship then displayes the whole path, which takes a lot of spaces and makes the header often not fit into one line.
Example:
```
kurscheidt in XXX at XXX on  master took 13s
➜ source activate really/really/really/really/really_long_path/envs/enviroment
kurscheidt in XXX at XXX on  master via 🅒 really/really/really/really/really_long_path/envs/enviroment
➜
```
I think a better way would be to only display the folder-name and not the whole path. I can consult conda if I want to know the whole path.

**Comment by avarun42** [comment]
I think this issue is irrelevant to `spacefish` since `spacefish` doesn't show the conda environment name at all, but only the conda version (which I think is useless but is a separate argument). Any display of conda environment that's happening is from conda itself. In `spaceship-prompt`, the prompt itself displays the active conda environment.

**Comment by matchai** [comment]
Good catch @avarun42! 😄 
You are completely right.

Closing this issue as it doesn't apply to spacefish.
