### ISSUE TITLE
Ability to use nerdfonts.

### ISSUE THREAD

**Issue by RatanShreshtha** [matchai/spacefish#177]
## Feature Request

It would be really nice if we can use [Nerd Fonts](https://nerdfonts.com) for different symbols and characters in the prompt and if it's possible then I would like to work on this feature.

**Comment by salmanulfarzy** [comment]
Font rendering is handled by terminal emulator. Installing nerd-fonts and configuring it with required `SPACEFISH_*_SYMBOL` would normally work. Did you face issues with using nerd-fonts with spacefish ?  Make sure to use the symbol codes.

Related denysdovhan/spaceship-prompt#401

**Comment by matchai** [comment]
That's correct.

If you are using fish, you can print Nerd Font symbols like so:
```fish
echo \uf898  # Prints the Node.js symbol
```

You can then customize the symbols that spacefish uses by customizing the variables associated to the symbols being printed. You can see a list of those options here: https://spacefish.matchai.me/docs/Options.html

**Comment by RatanShreshtha** [comment]
@matchai I am asking for ability to switch between nerd fonts and other font like the bobthefish theme has option to switch from patched powerline fonts to nerd fonts by using the configuration variable `set -g theme_nerd_fonts yes` in `config.fish`.

**Comment by salmanulfarzy** [comment]
Isn't that doing the [same behind the screen][1] ? How is that different from allowing the user to configure each symbol ?

[1]: https://github.com/oh-my-fish/theme-bobthefish/blob/e31962395f3b90ce12c1d185c9bf2e4671ddc5f0/functions/__bobthefish_glyphs.fish

**Comment by matchai** [comment]
Spacefish aims to achieve feature-parity with [spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt), the original prompt that this is a port of. I suggest new feature proposals be made at the spaceship repo, so that we can port it to spacefish when it gets approved. 🙂 

For the time being, you can use the existing configuration options to customize your prompt to match the symbols used in bobthefish:
https://github.com/oh-my-fish/theme-bobthefish/blob/fcec6aeece183e47bdad6e5356033114d4adee59/functions/__bobthefish_glyphs.fish#L57-L83

**Comment by RatanShreshtha** [comment]
Thanks @matchai I can pitch my idea there.
