### ISSUE TITLE
[FR] implement NERD FONT mode

### ISSUE THREAD

**Issue by mildc055ee** [matchai/spacefish#188]
## Feature Request
instead of using emoji, I wanna use icons of Nerd Font. I think in some case nerd icons represents better than emoji,(for example,current golang:🐹, aws:☁️)

**Describe the solution you'd like**
implement SPACEFISH_PROMPT_NERD_FONT
I'm just working on this work.

**Describe alternatives you've considered**
N/A (because this FR suggests an alternative to emoji)

sorry for my poor English, thanks.

**Comment by matchai** [comment]
Hi @mildc055ee! Thank you for opening an issue. 😄 

Spacefish aims to achieve feature-parity with [spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt/), the original prompt that this is a port of. I suggest new feature proposals be made at the spaceship repo, so that we can port it to spacefish when it gets approved.

**Comment by mildc055ee** [comment]
oh sorry, I got it.
thanks for your reply :)
